# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunny R. Juneja
email: jr.sunny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Sunny. I like writing about startups and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sunnyrjuneja.com" # the base hostname & protocol for your site
twitter_username: sunnyrjuneja
github_username:  sunnyrjuneja

# Build settings
markdown: kramdown
exclude: ['s3_website.yml', 'Gemfile', 'Gemfile.lock', 'bin']
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      comments: false
